Repository fourkitchens/sous-drupal-distro, pull requests merged in 2022-02, with the labels that each got.

#56 Change the admin theme to Gin and remove Claro
  composer.json
  config/install/system.theme.yml
  sous.info.yml
Labels: Passes Functional, Passes Code Review, Ready to merge

#46 feat: adding more standard packages based on request issue 3236449
  composer.json
Labels: bug

#57 Update README.md
  README.md
Labels: Needs work
